// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NameService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HeartBeat struct {
	Header               *ConnectionHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff7aff3b3ac208, []int{0}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetHeader() *ConnectionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ConnectionInfo struct {
	Header               *ConnectionHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConnectionInfo) Reset()         { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()    {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff7aff3b3ac208, []int{1}
}

func (m *ConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionInfo.Unmarshal(m, b)
}
func (m *ConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionInfo.Marshal(b, m, deterministic)
}
func (m *ConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionInfo.Merge(m, src)
}
func (m *ConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionInfo.Size(m)
}
func (m *ConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionInfo proto.InternalMessageInfo

func (m *ConnectionInfo) GetHeader() *ConnectionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ConnectionHeader struct {
	MessageServerId      string   `protobuf:"bytes,1,opt,name=message_server_id,json=messageServerId,proto3" json:"message_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionHeader) Reset()         { *m = ConnectionHeader{} }
func (m *ConnectionHeader) String() string { return proto.CompactTextString(m) }
func (*ConnectionHeader) ProtoMessage()    {}
func (*ConnectionHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ff7aff3b3ac208, []int{2}
}

func (m *ConnectionHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionHeader.Unmarshal(m, b)
}
func (m *ConnectionHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionHeader.Marshal(b, m, deterministic)
}
func (m *ConnectionHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionHeader.Merge(m, src)
}
func (m *ConnectionHeader) XXX_Size() int {
	return xxx_messageInfo_ConnectionHeader.Size(m)
}
func (m *ConnectionHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionHeader proto.InternalMessageInfo

func (m *ConnectionHeader) GetMessageServerId() string {
	if m != nil {
		return m.MessageServerId
	}
	return ""
}

func init() {
	proto.RegisterType((*HeartBeat)(nil), "proto.HeartBeat")
	proto.RegisterType((*ConnectionInfo)(nil), "proto.ConnectionInfo")
	proto.RegisterType((*ConnectionHeader)(nil), "proto.ConnectionHeader")
}

func init() { proto.RegisterFile("NameService.proto", fileDescriptor_98ff7aff3b3ac208) }

var fileDescriptor_98ff7aff3b3ac208 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf4, 0x4b, 0xcc, 0x4d,
	0x0d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x36, 0x5c, 0x9c, 0x1e, 0xa9, 0x89, 0x45, 0x25, 0x4e, 0xa9, 0x89, 0x25, 0x42, 0xfa,
	0x5c, 0x6c, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xe2,
	0x10, 0xb5, 0x7a, 0xce, 0xf9, 0x79, 0x79, 0xa9, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x1e, 0x60, 0xe9,
	0x20, 0xa8, 0x32, 0x25, 0x47, 0x2e, 0x3e, 0x84, 0x9c, 0x67, 0x5e, 0x5a, 0x3e, 0xe9, 0x46, 0xd8,
	0x71, 0x09, 0xa0, 0xcb, 0x09, 0x69, 0x71, 0x09, 0xe6, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0xc6,
	0x17, 0xa7, 0x16, 0x95, 0xa5, 0x16, 0xc5, 0x67, 0xa6, 0x80, 0xcd, 0xe3, 0x0c, 0xe2, 0x87, 0x4a,
	0x04, 0x83, 0xc5, 0x3d, 0x53, 0x8c, 0x42, 0xb8, 0xb8, 0x91, 0x3c, 0x27, 0xe4, 0xca, 0x25, 0x02,
	0x35, 0xce, 0x17, 0x59, 0xa1, 0x90, 0x00, 0xd4, 0x1d, 0x70, 0xcf, 0x4a, 0x89, 0x62, 0xb8, 0x0c,
	0xe4, 0x01, 0x25, 0x06, 0x0d, 0x46, 0x03, 0xc6, 0x24, 0x36, 0xb0, 0x9c, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x9e, 0xff, 0xaf, 0x84, 0x39, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NameServiceClient is the client API for NameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NameServiceClient interface {
	ConnectMessageServer(ctx context.Context, opts ...grpc.CallOption) (NameService_ConnectMessageServerClient, error)
}

type nameServiceClient struct {
	cc *grpc.ClientConn
}

func NewNameServiceClient(cc *grpc.ClientConn) NameServiceClient {
	return &nameServiceClient{cc}
}

func (c *nameServiceClient) ConnectMessageServer(ctx context.Context, opts ...grpc.CallOption) (NameService_ConnectMessageServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameService_serviceDesc.Streams[0], "/proto.NameService/ConnectMessageServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameServiceConnectMessageServerClient{stream}
	return x, nil
}

type NameService_ConnectMessageServerClient interface {
	Send(*HeartBeat) error
	Recv() (*ConnectionInfo, error)
	grpc.ClientStream
}

type nameServiceConnectMessageServerClient struct {
	grpc.ClientStream
}

func (x *nameServiceConnectMessageServerClient) Send(m *HeartBeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nameServiceConnectMessageServerClient) Recv() (*ConnectionInfo, error) {
	m := new(ConnectionInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NameServiceServer is the server API for NameService service.
type NameServiceServer interface {
	ConnectMessageServer(NameService_ConnectMessageServerServer) error
}

// UnimplementedNameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNameServiceServer struct {
}

func (*UnimplementedNameServiceServer) ConnectMessageServer(srv NameService_ConnectMessageServerServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectMessageServer not implemented")
}

func RegisterNameServiceServer(s *grpc.Server, srv NameServiceServer) {
	s.RegisterService(&_NameService_serviceDesc, srv)
}

func _NameService_ConnectMessageServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NameServiceServer).ConnectMessageServer(&nameServiceConnectMessageServerServer{stream})
}

type NameService_ConnectMessageServerServer interface {
	Send(*ConnectionInfo) error
	Recv() (*HeartBeat, error)
	grpc.ServerStream
}

type nameServiceConnectMessageServerServer struct {
	grpc.ServerStream
}

func (x *nameServiceConnectMessageServerServer) Send(m *ConnectionInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nameServiceConnectMessageServerServer) Recv() (*HeartBeat, error) {
	m := new(HeartBeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NameService",
	HandlerType: (*NameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectMessageServer",
			Handler:       _NameService_ConnectMessageServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "NameService.proto",
}
